### ISSUE TITLE
No images for album covers

### ISSUE THREAD

**Issue by killhellokitty** [othmar52/slimpd#11]
empty boxes where the album covers should be.

**Comment by othmar52** [comment]
Are you familiar with the inspector of your webbrowser? Or are you able to find out the URL/src-attribute of the `<img />`? 

In case you find the url please request it [with the debug parameter](https://github.com/othmar52/slimpd/issues/10#issuecomment-233781858) and post the response.

**Comment by killhellokitty** [comment]
failed to load image:/slimpd/index.php/image-1000/album/134

That is the error message recieved.  No I am not familiar with
locating URL/src-attribute
in web browser.

**Comment by killhellokitty** [comment]
http://127.0.0.1/slimpd/vendor/happyworm/jplayer/dist/jplayer/jquery.jplayer.swf
Failed to load resource: the server responded with a status of 404 (Not
Found)

Failed to load resource: the http://127.0.0.1/album/119?null&nosurrounding=1
Failed to load resource: the server responded with a status of 404 (Not
Found)

<a href="/album/119" data-ajaxtarget="#main" class="ajax-link">
<img src="/slimpd/index.php/image-100/album/119" style="width: 100px;
height: 100px;">
</a>

<img src="/slimpd/index.php/image-100/album/119" style="width: 100px;
height: 100px;">

Here is what I could find about the album images.

**Comment by othmar52** [comment]
could you right-click on the image box and choose "View Image" or "Open image in a new Tab" of the context-menu?
This should open the URL/src-attribute in a new tab where you can add the debug-parameter

**Comment by othmar52** [comment]
Oh - in the meantime you found the src-attribut. :)
what is the response of  [http://127.0.0.1/slimpd/index.php/image-100/album/119?debug](http://127.0.0.1/slimpd/index.php/image-100/album/119?debug) ?

**Comment by othmar52** [comment]
> http://127.0.0.1/slimpd/vendor/happyworm/jplayer/dist/jplayer/jquery.jplayer.swf
> Failed to load resource: the server responded with a status of 404 (Not Found)
[fixed](https://github.com/othmar52/slimpd/commit/5e3c0214d73a76f507af436baa09725875a39783)

**Comment by killhellokitty** [comment]
It gives a blank page again. Nothing.

**Comment by killhellokitty** [comment]
No change.
Btw.  It does play and list all my music files.  So, the permissions should
be good.

**Comment by killhellokitty** [comment]
Hey, I did get this debug message for systemcheck:

Slim Application Error

The application could not run because of the following error:
Details
*Type:* Twig_Error_Loader
*Message:* Unable to find template
"partials/systemcheck/waveforms/wfM4a-danger.htm" (looked into: templates)
in "systemcheck.htm" at line 173.
*File:*
 /srv/http/slimpd/vendor-dist/twig/twig/lib/Twig/Loader/Filesystem.php
*Line:* 215
Trace

#0 /srv/http/slimpd/vendor-dist/twig/twig/lib/Twig/Loader/Filesystem.php(139):
Twig_Loader_Filesystem->findTemplate('partials/system...')
#1 /srv/http/slimpd/vendor-dist/twig/twig/lib/Twig/Environment.php(312):
Twig_Loader_Filesystem->getCacheKey('partials/system...')
#2 /srv/http/slimpd/vendor-dist/twig/twig/lib/Twig/Environment.php(378):
Twig_Environment->getTemplateClass('partials/system...', NULL)
#3 /srv/http/slimpd/vendor-dist/twig/twig/lib/Twig/Template.php(286):
Twig_Environment->loadTemplate('partials/system...', NULL)
#4 /srv/http/slimpd/vendor-dist/twig/twig/lib/Twig/Environment.php(403)
: eval()'d code(531):
Twig_Template->loadTemplate('partials/system...', 'systemcheck.htm',
173)
#5 /srv/http/slimpd/vendor-dist/twig/twig/lib/Twig/Template.php(387):
__TwigTemplate_3ddfa5c85feb2645fee990c2d5537f5e9240bb8d06bb48b863457e5fbf805077->doDisplay(Array,
Array)
#6 /srv/http/slimpd/vendor-dist/twig/twig/lib/Twig/Template.php(355):
Twig_Template->displayWithErrorHandling(Array, Array)
#7 /srv/http/slimpd/vendor-dist/twig/twig/lib/Twig/Template.php(366):
Twig_Template->display(Array)
#8 /srv/http/slimpd/vendor-dist/slim/views/Twig.php(91):
Twig_Template->render(Array)
#9 /srv/http/slimpd/vendor-dist/slim/slim/Slim/View.php(255):
Slim\Views\Twig->render('systemcheck.htm', Array)
#10 /srv/http/slimpd/vendor-dist/slim/slim/Slim/View.php(243):
Slim\View->fetch('systemcheck.htm', NULL)
#11 /srv/http/slimpd/vendor-dist/slim/slim/Slim/Slim.php(757):
Slim\View->display('systemcheck.htm')
#12 /srv/http/slimpd/php/routes/get.php(1330):
Slim\Slim->render('systemcheck.htm', Array)
#13 [internal function]: {closure}()
#14 /srv/http/slimpd/vendor-dist/slim/slim/Slim/Route.php(468):
call_user_func_array(Object(Closure), Array)
#15 /srv/http/slimpd/vendor-dist/slim/slim/Slim/Slim.php(1357):
Slim\Route->dispatch()
#16 /srv/http/slimpd/vendor-dist/slim/slim/Slim/Middleware/Flash.php(85):
Slim\Slim->call()
#17 /srv/http/slimpd/vendor-dist/slim/slim/Slim/Middleware/MethodOverride.php(92):
Slim\Middleware\Flash->call()
#18 /srv/http/slimpd/vendor-dist/slim/slim/Slim/Middleware/PrettyExceptions.php(67):
Slim\Middleware\MethodOverride->call()
#19 /srv/http/slimpd/vendor-dist/slim/slim/Slim/Slim.php(1302):
Slim\Middleware\PrettyExceptions->call()
#20 /srv/http/slimpd/index.php(122): Slim\Slim->run()
#21 {main}

**Comment by othmar52** [comment]
i think i have found the reason for the broken images. on my test-setups the package imagemagick was available which has its binary under `/usr/bin/convert`
pretty sure you dont have it on your machine so image-processing does not work. 

i have to to take a closer look at the phpThumb library i have used to remove the requirement of the imagemagick-package.

**Comment by killhellokitty** [comment]
I have imagemagick installed.  I also have php-imagemagik installed and
enabled.

**Comment by othmar52** [comment]
> *Message:* Unable to find template
> "partials/systemcheck/waveforms/wfM4a-danger.htm" (looked into: templates)
> in "systemcheck.htm" at line 173.

M4a-template issue is [fixed](https://github.com/othmar52/slimpd/commit/25bcf2b0cbb6c0aa1c0bebaa069c5f7032c270b6) - so /systemcheck should work again

**Comment by othmar52** [comment]
> Btw.  It does play and list all my music files.  So, the permissions should
> be good.
While playing with mpd other permissions are relevant as it has nothing to do with webbrowser/lighttpd.
are you able to play files in the "local player"?

**Comment by killhellokitty** [comment]
Okay, the systemcheck is fixed.
It still says that my music folder and mpd-database permission are wrong.
I showed you the list of permissions for those folders and files and 'http'
and 'root' have permission per use of 'acl'.  It should have worked
according to everything i have read about 'acl' for permissions.  I just
really hate to have to create a new partition/file for Music under root and
install mpd for root environment.  But it is looking more and more as
though that is what I will have to do to get this to work properly.  I'll
have a go at changing all that up tomorrow.  As for 'local player' I'm not
sure what that means/is?

**Comment by othmar52** [comment]
> As for 'local player' I'm not sure what that means/is?

at the very left bottom in slimpd-gui you can toggle between controlling mpd and playing files directly in browser. in case local play does not work it wouldn't be that suprising that /filbrowser?null does not work because of permission problems

**Comment by killhellokitty** [comment]
local player doesn't work.  I'll get back to you tomorrow after I reinstall
Mpd to root env. and move Music to root as well.
Thank for the help today.  Im gonna crash.

**Comment by othmar52** [comment]
after moving your files images work?

**Comment by killhellokitty** [comment]
More than 1/2 work the rest don't show up.  I'm not sure if it has to do
with the naming of the album cover file or what exactly.  It also looks
like you designed it to show multiple album images.  Front, back,
insert...am I correct?  If so, how does one go about using the multiple
images?

**Comment by othmar52** [comment]
Unfortunately weightening of images is not implemented yet. I have added a new [wiki page](https://github.com/othmar52/slimpd/wiki/Configuration) clear things up what's possible at the moment.

**Comment by killhellokitty** [comment]
Also, well preserved and documented extracted album content is layed out
like so:

My Album
├── Artwork
│   ├── Front.jpg *
│   └── Back.jpg *
├── Disc 1
│   ├── Track 01.flac
│   └── Track 02.flac
└── Disc 2

So the artwork has a separate folder altogether.

**Comment by killhellokitty** [comment]
Also, I have found that the album images that were not imported where
embedded images.  They were folders without a cover.jpg or other album
artwork file.  All the files in the folder were embedded with the album
artwork images.  It appears that 'read_embedded' has an issue.

**Comment by othmar52** [comment]
> My Album
> ├── Artwork
> │   ├── Front.jpg *
> │   └── Back.jpg *
> ├── Disc 1
> │   ├── Track 01.flac
> │   └── Track 02.flac
> └── Disc 2
> 
> So the artwork has a separate folder altogether.

As you can see in the documentation, this case not covered at the moment. but it shouldn't be that hard for me to implement this. i will try this tomorrow.


>It appears that 'read_embedded' has an issue.

maybe i should add another systemcheck for extracting an embedded image. Would be great if you can provide me a testfile with an embedded image - as tiny as possible.

**Comment by othmar52** [comment]
> As you can see in the documentation, this case not covered at the moment. but it shouldn't be that hard for me to implement this. i will try this tomorrow.

please pull the [latest commits](https://github.com/othmar52/slimpd/commit/962a72d32176a9b74ad78a1f21fad97dde616b73) and give it a try. Unfortunately currently you have to empty your database and re-import again

**Comment by killhellokitty** [comment]
Emptied my database and started from scratch.  Most embedded images were saved and used, but not all.  There are still many music files with embedded album images only (no cover.jpg...etc in the folder) that were not added to the database.  The images were of different file types: flac, mp3, so I could not find a commonality between why they did not import.

**Comment by othmar52** [comment]
i had implemented a size limit for embeded images because one of the external libraries (i dont know which one) had a problem like `Maximum supported image dimension is 65500 pixels`.

Anyway - [i have deactivated this check](https://github.com/othmar52/slimpd/commit/59721356e27680c86f5998f44ad6c48879ca876c) and now all your embedded images should appear after a re-import.

Hopefully i find a musicfile with this mentioned error to implement a proper solution. Maybe you are able to create such a testfile with an enourmously huge embedded image?

**Comment by killhellokitty** [comment]
I don't have any music files with larger album art than the one I sent you
"skulls".  I hadn't noticed, but it is a rather large image.  Glad to hear
you found the issue.
I imagine you have imagemagik setup to shrink the images to the appropriate
size anyway.
I tried to embed a music file with a desktop-wallpaper image 1920x1920 and
it refused to add the image to the file, to large.  Sorry.

**Comment by othmar52** [comment]
> I imagine you have imagemagik setup to shrink the images to the appropriate
> size anyway.

If i remember correctly the embedded image gets extracted without beeing modified or resized.
Only when beeing displayed in the browser resized duplicates will be created while leaving the original in `embedded/*` untouched

> I tried to embed a music file with a desktop-wallpaper image 1920x1920 and
> it refused to add the image to the file, to large.  Sorry.

Thanks for trying! the next "hard-reset" of my sliMpd production instance will show me such a file. As my initial import takes several days i will wait for some new importer improvements before my next reset.
