### ISSUE TITLE
Artist names with 'the' '&' 'and' break ability to select.

### ISSUE THREAD

**Issue by killhellokitty** [othmar52/slimpd#12]
Artists who's names have 'the' '&' 'and' break the ability to select that artist in the Artist page, and elsewhere.  For example, The Creatures; it lists how many tracks are next to the name, search allows selection of a specific title by The Creatures. But I can't select The Creatures as an artist on the Artist page.

**Comment by othmar52** [comment]
maybe the reason was issue #16 ?
or does the problem still exist?

**Comment by killhellokitty** [comment]
The issue is gone as of today.  It must have been related to #16.
