### ISSUE TITLE
detail page of artist, genre, label gives zero results

### ISSUE THREAD

**Issue by othmar52** [othmar52/slimpd#16]
each item which's id is lower than 10 has a broken detail page

**possible solution A**
change sphinx-configuration from
```
index slimpdmain
{
  min_prefix_len    = 2
}
```
to
```
index slimpdmain
{
  min_prefix_len    = 1
}
```

**possible solution B**
Before starting to fill the MySQL database do `ALTER TABLE `tablename` AUTO_INCREMENT = 10;` on each table

**Comment by killhellokitty** [comment]
Changed the slimpdmain index.  I tried to change the mysql :ALTER TABLE
 slimpd AUTO_INCREMENT = 10; but i just get errors.  I'm not that well
versed in mysql.

**Comment by othmar52** [comment]
[resolved](https://github.com/othmar52/slimpd/commit/0d0c1bb692ba65a67baf2927c0c946c8ddaae822) with **solution B** because solution A will bloat the sphinx index too much on really huge collections.

unfortunately a complete re-indexing is necessary :/
