### ISSUE TITLE
Breaking up of Aritst name when '&' are in artist name.

### ISSUE THREAD

**Issue by killhellokitty** [othmar52/slimpd#19]
A good example is 'Siouxsie & the Banshees'.  The artist page divides the artist into 2 artists.  'The Banshees' and 'Siouxsie'.  Both have the same tracks and track listings under their header.  But again they are listed as separate artists even on the 'now playing' page.  It seems the '&' breaks the name into 2 artists.

**Comment by othmar52** [comment]
this is a feature :)
imagine you also have [this release](https://www.discogs.com/de/Siouxsie-Mantaray/master/114395) in your collection. Isn't it better to display this release as well when navigating to "Siouxsie"'s detail page?

In case you want to display just the collaborative tracks you have to click directly on the ampersand ` & ` between those artists.

**Comment by killhellokitty** [comment]
I understand your point and  it is thoughtful and valid.  It does make a huge difference with my techno/house/etc.  I'd mark this one as closed.
