### ISSUE TITLE
Artist Search doesn't respect spaces in naming

### ISSUE THREAD

**Issue by killhellokitty** [othmar52/slimpd#23]
The ArtistList, Artist Search area doesn't respect 'spaces' in Artist names.   For example it returns 'artist not found' when I type in 'Felix da Housecat' (caps or no caps).  But, it returns all listing of the artist when the artist's name is typed in as 'felixdahousecat'.  It seems to me that both should work.  I don't know if this was intentional on your part.

**Comment by othmar52** [comment]
your are right. this "alpha search" was the very first search possibility, long before the sphinx based "main search" was available.
now it should work with most special characters. `#` and `/` characters in searchterm are still problematic

**Comment by killhellokitty** [comment]
Fixed.
