### ISSUE TITLE
Importing of library giving errors

### ISSUE THREAD

**Issue by killhellokitty** [othmar52/slimpd#28]
After deleting and updating Mpd-database (checked in a Ncmpcpp database is present and correct and working), removing Mysql-database and re-creating it; running 'php cli-update.php update-db-scheme' and then 'php cli-update.php standard'; and finally updating Sphinx.  I recieve this message with all files I try to play:
_OH Snap!
Felix Da Housecat/Felix Da Housecat/Felix da Housecat - Virgo Blaktro and the Movie Disco (2007)/02. MovieDisco - Felix da Housecat.MP3 does not exist in MPD-database.
updating Felix Da Housecat/Felix Da Housecat/Felix da Housecat - Virgo Blaktro and the Movie Disco (2007)_

I have checked the Mysql-database itself and the entries are correct.  I have checked the Mpd-database with other clients and it is correct and working.  I have restarted the computer, just to be on the safe side; it has no affect.  

Something has gone amiss with the 'php cli-update.php standard'  command.  It runs VERY quickly compared to how it did previously.  Heres its last output with this import:

_STARTING import phase 1 processMpdDatabasefile()
dircount: 339
songs: 2872
dead songs: 0
FINISHED import phase 1 processMpdDatabasefile()
STARTING import phase 2 scanMusicFileTags()
progress:38%
progress:39%
progress:39%
FINISHED import phase 2 scanMusicFileTags()
STARTING import phase 3 migrateRawtagdataTable()
progress:81%
FINISHED import phase 3 migrateRawtagdataTable()
STARTING import phase 4 destroyExtractedImageDupes()
Deleted 8 images with a total size of 2.17 MB
FINISHED import phase 4 destroyExtractedImageDupes()
STARTING import phase 5 searchImagesInFilesystem()
progress:38%
progress:89%
FINISHED import phase 5 searchImagesInFilesystem()
STARTING import phase 8 fixAlbumLabels()
FINISHED import phase 8 fixAlbumLabels()
STARTING import phase 9 updateCounterCache()
FINISHED import phase 9 updateCounterCache()
STARTING import phase 10 extractAllMp3FingerPrints()
FINISHED import phase 10 extractAllMp3FingerPrints()_

For some reason its just not connecting to Mpd-database and doing proper importing.

**Comment by othmar52** [comment]
i am not able to reproduce this error so its pretty hard to find the reason. in the meantime some external libraries (including getid3) had been updated.

would you jump to the latest commit before this update and try to reproduce this error?
```
git checkout a2991f8c6dd708d5e0a0dfe667d4516671093078
```

to switch back to a valid branch in the git repo you have to
```
git checkout master
```
after this test


Are you able to say which "phase(s)" of the `cli-import.php` feels so much faster?

**Comment by killhellokitty** [comment]
The tracks are now listed as M4A's.

The cli-import.php just takes seconds now, when before it took 4min or so.
It doesn't show any progress/import with things like the Mp3 fingerprints
which took a long time before.  Here is the print out of my latest attempt:

STARTING import phase 1 processMpdDatabasefile()
dircount: 339
songs: 2872
dead songs: 0
FINISHED import phase 1 processMpdDatabasefile()
STARTING import phase 2 scanMusicFileTags()
progress:39%
FINISHED import phase 2 scanMusicFileTags()
STARTING import phase 3 migrateRawtagdataTable()
progress:88%
FINISHED import phase 3 migrateRawtagdataTable()
STARTING import phase 4 destroyExtractedImageDupes()
Deleted 8 images with a total size of 2.17 MB
FINISHED import phase 4 destroyExtractedImageDupes()
STARTING import phase 5 searchImagesInFilesystem()
FINISHED import phase 5 searchImagesInFilesystem()
STARTING import phase 8 fixAlbumLabels()
FINISHED import phase 8 fixAlbumLabels()
STARTING import phase 9 updateCounterCache()
FINISHED import phase 9 updateCounterCache()
STARTING import phase 10 extractAllMp3FingerPrints()
FINISHED import phase 10 extractAllMp3FingerPrints()

It looks like it is only reading a few entries and omitting everything
else.  All the tracks I have pulled up so far say "track not imported yet"
in a red box.  Anouther thing, the 'destroyingExtractedImagesDupes() only
deletes 8 images total size of 2.17Mb, before it was over 13Mb it was
deleting.
I can't for the life of me figure whats going on.  Mpd clients show and
play the library without issue.

**Comment by killhellokitty** [comment]
I just thought of something.  Might it be having problems with 'Album
Artist' being used?  "Artist", and "Album Artist", because I did add "Album
Artist' to the 1d3 tags.  Or maybe its because I upgraded to ID3v2.4 tags?
That still doesn't account for files with Flac vorbiss tags not showing up
either.  Just a couple thoughts.

**Comment by killhellokitty** [comment]
Here is an image of the Track Info View.  Notice all the missing information.  Something with import is wrong.  I've tried reimporting many times now and receive the same results.  
http://i725.photobucket.com/albums/ww260/killhellokitty1/Screenshot%20from%202016-07-30%2012-58-29_zpsldramrab.png

**Comment by killhellokitty** [comment]
Here is a screenshot of the "dump metadata" page.  It does look like we
have a problem.  Let me know what you think.
http://i725.photobucket.com/albums/ww260/killhellokitty1/Screenshot%20from%202016-07-31%2011-41-50_zpsaeu0cljj.png

**Comment by killhellokitty** [comment]
Here is screenshot of my rawtagdata for a couple tracks.  There is an
import error in the last colomn.  Something is a miss.  I wonder what ID3
tags are supported by 'GETID3'?
http://i725.photobucket.com/albums/ww260/killhellokitty1/rawtagdata-josh-pg2_zpshfo0c2vm.png

**Comment by othmar52** [comment]
Hmm, the errormessage of get id3 says that the file could not be opened at all. is it possible that your permission-problem is back or do you have an invalid path in the url?

`http://localhost/slimpd/maintainance/trackid3/relative-filepath-without-mpd-musicdir`

**Comment by killhellokitty** [comment]
url gives me a 404 error.  I have checked the permissions on the music
directory, folders, and files and they are the same as before owner is root
rw, group is users r, others r.  SliMPD has owner is http rw, group is root
r, others r.

**Comment by othmar52** [comment]
i think a found the reason. thanks to your testfiles i was able to reproduce this problem. Obviously i modified the filepath in the database when trying to remove html stuff of id3-tags. As your files have multiple whitespaces in filename `02 - 04.[2 whitespaces]Thieves Like Us - New Order.FLAC` this BUG affected your import.

Please pull the latest [commit](https://github.com/othmar52/slimpd/commit/0212285a3f2c1394204ef0e1a871afb375a5ca4f) and try again

**Comment by killhellokitty** [comment]
You got it!  So it was the whitespaces...lol.  I'm glad you figured it
out.  Thank You.
Works fine now.

You should use the same album to look at the weighted images.  I believe it
gives an excellent example.
