### ISSUE TITLE
flac waveform conversion script

### ISSUE THREAD

**Issue by killhellokitty** [othmar52/slimpd#29]
This will convert flac to mp3 to wav to create your waveform.  I am not sure if you can use --stdout within a webpage??   I hope that it is fine to use.  If so this should do the trick.

`/usr/bin/flac -d --stdout '/srv/http/slimpd/templates/partials/systemcheck/waveforms/testfiles/testfile-online-convert.com.flac' | /usr/bin/lame -m m -S -f -b 16 --resample 8 - '/srv/http/slimpd/cache/flac.d84bd2fdeb119b724e3441af376d7159.mp3' && lame -S --decode '/srv/http/slimpd/cache/flac.d84bd2fdeb119b724e3441af376d7159.mp3' '/srv/http/slimpd/cache/flac.d84bd2fdeb119b724e3441af376d7159.wav'
`

**Comment by othmar52** [comment]
thank you for that one. seems reasonable to me. the downside is another system requirement (flac binary) but i think the tiny sliMpd target group can live with that :)
