### ISSUE TITLE
WMA waveform conversion script

### ISSUE THREAD

**Issue by killhellokitty** [othmar52/slimpd#33]
This one uses Mplayer (and FFmpeg, through mplayer).  Its kinda strange it plays the audio file and rerecords it to WAV file, then the WAV to MP3 to WAV happens like in most of the other conversions.  I have not tested this to make sure it works properly, I have no WMA's.  You may want to test it first, if you choose to use it.

`/usr/bin/mplayer -really-quiet '/srv/http/slimpd/templates/partials/systemcheck/waveforms/testfiles/testfile-online-audio-converter.com.wma' -ao pcm:file='/srv/http/slimpd/cache/wma.06a76631d599a699e93ea9462f7f0feb.wav' && /usr/bin/lame -m m -S -f -b 16 --resample 8 '/srv/http/slimpd/cache/wma.06a76631d599a699e93ea9462f7f0feb.wav' '/srv/http/slimpd/cache/wma.06a76631d599a699e93ea9462f7f0feb.mp3' && lame -S --decode '/srv/http/slimpd/cache/wma.06a76631d599a699e93ea9462f7f0feb.mp3' '/srv/http/slimpd/cache/wma.06a76631d599a699e93ea9462f7f0feb.wav'
`

**Comment by othmar52** [comment]
> Its kinda strange it plays the audio file and rerecords it to WAV file,

as waveform generating is done on demand and not in advance its not a good solution. imagine you have some `multiple-hours-dj-mix.wma`.  Will the process of generating also last that long?

**Comment by killhellokitty** [comment]
I really don't know.  For WMA and AC3 the Mplayer conversion seems to be
preferred.  They could always be changed to use FFmpeg alone I suppose.
These 2 leave questions.  They would need to be tried out.

**Comment by othmar52** [comment]
this seems to work perfectly - thank you!
