### ISSUE TITLE
New Gallery wiki page

### ISSUE THREAD

**Issue by killhellokitty** [othmar52/slimpd#36]
I took all the images from what you now have as your wiki's HOME page and created a new markdown file for it as your wiki's GALLERY page.  
The HOME page needs to be a page explaining what sliMPD is and what it does and most importantly what is special about it.  It a who am I page for the app.  If you have the time to write it out in plain text, I will gladly format it in markdown and create the page for you.

The changes I made to the GALLERY page are most notably that I divided the page into a table of 3 columns wide, with the image and its information in each cell.  It makes the page easier to browse through; and of course selecting an image expands it to full page size.

You can download the markdown here:  http://pastebin.com/1hy8UKFX

I hope you like it!

**Comment by othmar52** [comment]
> ...If you have the time to write it out in plain text, I will gladly format it in
> markdown and create the page for you.

I will give it a try very soon.

> ...I divided the page into a table of 3 columns wide...

I can imagine that i would prefer a 2 columns layout to have bigger thumbnails but i am not sure about. maybe i am going to change this after i tried it.

> I hope you like it!

Yeah, impressive work! Thank you very much

**Comment by killhellokitty** [comment]
I rewrote the Gallery-wiki.  Its much cleaner and has a menu at the top of
the page.
If you would prefer it to be 2 columns let me know and I will make the
change.

Please use this new version:  http://pastebin.com/1hy8UKFX

**Comment by othmar52** [comment]
Adding the top menu was a good idea - thank you very much! 
btw i think you do have permission to edit the othmar52/slimpd-wiki directly!?
