### ISSUE TITLE
New Configuration wiki

### ISSUE THREAD

**Issue by killhellokitty** [othmar52/slimpd#37]
Here you go, a thorough, I might even say complete wiki for the configuration of the config_local.ini.
I worked really hard on this one, and intend on rewriting the Installation-wiki to be more thorough and match the style of this wiki.  If its alright with you.

I hope you like this one, feel free to add any info I may have omitted or had not commented on thoroughly enough.

Copy form Pastebin:  http://pastebin.com/a97yZkYi

Cheers!
Josh

**Comment by othmar52** [comment]
> ...I worked really hard on this one ...

Yes that can't be missed. Thank you so much!
