### ISSUE TITLE
sphinx service doesn't start

### ISSUE THREAD

**Issue by eoli3n** [othmar52/slimpd#42]
Installed sphinx from aur packages : https://aur.archlinux.org/packages/sphinx/
I copied sphinx template and then edit to slimpddb access

```
source srcslimpdbase
{
  type              = mysql
  sql_host          = localhost
  sql_user          = slimpduser
  sql_pass          = slimpd
  sql_db            = slimpddb
  sql_port          = 3306
  sql_ranged_throttle = 0
}
```

full sphinx.conf : http://sprunge.us/TBhY

Then 

```
⚡ root@osz  ~  systemctl start sphinx
Job for sphinx.service failed because the control process exited with error code.
See "systemctl status sphinx.service" and "journalctl -xe" for details.
✘ ⚡ root@osz  ~  systemctl status sphinx.service
● sphinx.service - Sphinx - SQL Full Text Search Engine
   Loaded: loaded (/usr/lib/systemd/system/sphinx.service; disabled; vendor preset: disabled)
   Active: failed (Result: start-limit-hit) since mer. 2016-10-26 18:25:32 CEST; 6s ago
  Process: 6762 ExecStart=/usr/bin/searchd --config /etc/sphinx/sphinx.conf (code=exited, status=1/FAILURE)

oct. 26 18:25:31 osz systemd[1]: Failed to start Sphinx - SQL Full Text Search Engine.
oct. 26 18:25:31 osz systemd[1]: sphinx.service: Unit entered failed state.
oct. 26 18:25:31 osz systemd[1]: sphinx.service: Failed with result 'exit-code'.
oct. 26 18:25:32 osz systemd[1]: sphinx.service: Service hold-off time over, scheduling restart.
oct. 26 18:25:32 osz systemd[1]: Stopped Sphinx - SQL Full Text Search Engine.
oct. 26 18:25:32 osz systemd[1]: sphinx.service: Start request repeated too quickly.
oct. 26 18:25:32 osz systemd[1]: Failed to start Sphinx - SQL Full Text Search Engine.
oct. 26 18:25:32 osz systemd[1]: sphinx.service: Unit entered failed state.
oct. 26 18:25:32 osz systemd[1]: sphinx.service: Failed with result 'start-limit-hit'.
```

**Comment by othmar52** [comment]
does those log paths of sphinx.conf exist on your system?
```
        log                             = /var/lib/log/searchd.log
        query_log                       = /var/lib/log/query.log
        pid_file                        = /var/lib/log/searchd.pid
```
is there any useful information in those log-files?

maybe you could try strace - sometimes its really helpul for these type of errors
```
strace systemctl status sphinx.service
```

**Comment by othmar52** [comment]
maybe you should combine the aur-shipped sphinx.conf with sliMpd-shipped sphinx.conf
<pre>
source srcslimpdbase {
  use <strong>sliMpd</strong>'s sphinx.conf and modify credentials
}
source srcslimpdsuggest: srcslimpdbase {
  use <strong>sliMpd</strong>'s sphinx.conf
}
source srcslimpdmain: srcslimpdbase {
  use <strong>sliMpd</strong>'s sphinx.conf
}
index slimpdsuggest {
  use <strong>sliMpd</strong>'s sphinx.conf and make sure path exists
}
index slimpdmain 
  use <strong>sliMpd</strong>'s sphinx.conf and make sure path exists
}
indexer {
 use <strong>aur</strong>'s sphinx.conf
}
searchd {
 use <strong>aur</strong>'s sphinx.conf
}
common {
  use <strong>aur</strong>'s sphinx.conf
}
</pre>

**Comment by eoli3n** [comment]
I did, and there are same, exept log file, so i found it and 

- searchd.log

    [Thu Oct 27 14:20:20.510 2016] [29143] watchdog: main process 29144 forked ok
    [Thu Oct 27 14:20:20.516 2016] [29144] listening on all interfaces, port=9312
    [Thu Oct 27 14:20:20.518 2016] [29144] listening on all interfaces, port=9306
    [Thu Oct 27 14:20:20.523 2016] [29144] WARNING: index 'slimpdsuggest': preload: failed to open /var/lib/data/slimpdsuggest.sph: No such file or directory; NOT SERVING
    [Thu Oct 27 14:20:20.524 2016] [29144] WARNING: index 'slimpdmain': preload: failed to open /var/lib/data/slimpdmain.sph: No such file or directory; NOT SERVING
    [Thu Oct 27 14:20:20.524 2016] [29144] FATAL: no valid indexes to serve
    [Thu Oct 27 14:20:20.528 2016] [29143] watchdog: main process 29144 exited cleanly (exit code 1), shutting down

**Comment by othmar52** [comment]
Hi
did you run the initial index-create command like statet in the the [sliMpd-documentation](https://github.com/othmar52/slimpd/wiki/Installation#create-sphinx-database)

>The first time after setting up Sphinx you must run:
>
>```
>root@your-machine $ indexer slimpdmain slimpdsuggest
>```

**Comment by othmar52** [comment]
@eoli3n do you still have problems with sphinx?

**Comment by othmar52** [comment]
i tried the same on an arch box with AUR sphinx in after running
```
root@your-machine $ indexer slimpdmain slimpdsuggest
```
everything worked. so i am goingt to clode this issue....
