### ISSUE TITLE
Importing mpd db stops at ~28% (phase 3)

### ISSUE THREAD

**Issue by clkmsc** [othmar52/slimpd#44]
Every time I try to import my mpd db file, it stops without reporting an error at around 28% of phase 3.

I assume it might be related to the contents of the db file, but MPD works fine. How can I go about debugging this?

Everything else is reported as OK in systemcheck (except empty index pending the import)

```
[clk@kzsrv slimpd]$ ./slimpd hard-reset
All data of database:slimpddb will be lost! Continue? [y/n]
y
Dropping database
Recreating database
Deleting files and directories inside localdata/cache/
Deleting files and directories inside localdata/embedded/
Deleting files and directories inside localdata/peakfiles/
STARTING import phase 0 triggerImport()
STARTING import phase 1 waitForMpd()
mpd seems to be ready. continuing...
FINISHED import phase 1 waitForMpd()
STARTING import phase 2 processMpdDatabasefile()
dircount: 5802
songs: 37636
dead songs: 0
FINISHED import phase 2 processMpdDatabasefile()
STARTING import phase 3 run()
progress:0.11%
[...content removed...]
progress:27.76%
progress:27.90%
[clk@kzsrv slimpd]$ 
```

**Comment by othmar52** [comment]
Thanks for reporting!
> How can I go about debugging this?

Maybe increasing verbosity helps to figure out where it stops!?
```ini
[config]
; 1 = quiet, 10 = maximal verbosity
cli-verbosity = 10
```

**Comment by clkmsc** [comment]
Thanks for the reply. I forgot to mention that I have already increased verbosity to 10 and there did not appear to be any additional output during this process. But you reminded me that I had previously experienced an issue where the slimpd script was referring to variables which I had already changed in the config file. 

I am still not sure where these variables get cached, but by backing up my config and cloning again, I am now able to see the verbose output. Sure enough, the file it breaks on has corrupted embedded cover art. I will fix the id3 tag, update again, and report back.

**Comment by othmar52** [comment]
Can you send me the corrupt file please?
I would like to fix the error on the sliMpd side.

**Comment by clkmsc** [comment]
Here is an example file. I actually found about 10 such files in my collection, and fixing them has allowed me to complete phase 3.
[mp3_corrupted_id3_image.zip](https://github.com/othmar52/slimpd/files/644771/mp3_corrupted_id3_image.zip)

Thanks for your help.

**Comment by clkmsc** [comment]
I'm all set now, but thought you'd like to know I noticed similar behavior in phase 5. If external cover art is corrupted the script will also throw a fatal error. Don't ask why I have so much corrupted art :) -- I think it's caused by [bliss](https://www.blisshq.com).

**Comment by othmar52** [comment]
Thanks for the file with the corrupt image!
Too bad i was not able to reproduce the error. None of my test-instances (on 3 different machines) did complain about the file.
![slimpd-corrupt-image](http://gas-werk.org/slimpd/slimpd-corrupt-image.png)

> ...If external cover art is corrupted the script will also throw a fatal error.

would you mind to tell me the exact error?

**Comment by clkmsc** [comment]
Weird. Fyi I am using lighttpd with PHP v7.0.14. The error looked like this:

```
PHP Warning:  imagecreatefromjpeg(): gd-jpeg, libjpeg: recoverable error: Corrupt JPEG data: premature end of data segment

 in /data/Documents/web/slimpd/core/vendor-dist/ksubileau/color-thief-php/lib/ColorThief/Image/Adapter/GDImageAdapter.php on line 42

PHP Fatal error:  imagecreatefromjpeg(): gd-jpeg: JPEG library reports unrecoverable error: Unsupported marker type 0x79 in /data/Documents/web/slimpd/core/vendor-dist/ksubileau/color-thief-php/lib/ColorThief/Image/Adapter/GDImageAdapter.php on line 42
```

No such error appeared in the output during phase 3 but I suspect they are similar.

**Comment by othmar52** [comment]
Thats kinda strange!
I also had this error during development but since 807023a4abf9e903129987f692941a13f46c169b slimpd's script-run should ignore this specific error.

Anyway  - i will do some further investigations on that issue. but for now it has not that much priority.
thank you very much!

**Comment by othmar52** [comment]
Theoretically i have solved this issue inside the external library https://github.com/ksubileau/color-thief-php .
Before i create a pull-request of https://github.com/othmar52/color-thief-php/commit/1b531fed50df97203c8d126ed8e83815aea8908b i'd like to reproduce this error.

extracting the bitmap of your attached mp3 obviously was not currupt enough. trying to currupt an imagefile by writing random ascii into the file also did not help.

would you mind to send me a corrupt image file :)

**Comment by clkmsc** [comment]
I already cleaned up my corrupted images, but may have one in a backup. I'll check and get back to you. However, based on what I've seen I would expect that the corrupted image extracted from the mp3 would trigger the error on my machine. I.e. I'm not sure even if I find one you will be able to reproduce it, if somehow it is specific to my setup.

**Comment by clkmsc** [comment]
We're in luck. I found a back up of one of the images that caused this error. 
![cover](https://cloud.githubusercontent.com/assets/778005/21164049/b4d543f6-c164-11e6-87ba-32c145709593.jpg)

**Comment by othmar52** [comment]
great! thank you very much!
@see https://github.com/ksubileau/color-thief-php/pull/30#issuecomment-267083994

**Comment by clkmsc** [comment]
No problem. Thank you for the help, and for slimpd :)
