### ISSUE TITLE
Translations.

### ISSUE THREAD

**Issue by killhellokitty** [othmar52/slimpd#6]
About a third of the labeling and text are only in German language.  English translations would be greatly appreciated.

**Comment by othmar52** [comment]
please add some url-schemas or a description where those translations are missing.
thank you

**Comment by othmar52** [comment]
i have added a few more translations [commit/777...bc2](https://github.com/othmar52/slimpd/commit/777e8c76edee52683c1bed7edc7060a2876eabc2)

Feel free to improve existing translations or add some more because my english is not that good

**Comment by killhellokitty** [comment]
I've added a pullrequest for some translations...sorry the request is a bit messy, my first time doing one.  Also an addition to the config/config.ini. in the pullrequest.

**Comment by killhellokitty** [comment]
Their are still more items that need to be translated, I just don't know where to find them.  'Aktueller Titel' is at the top of the page right before track title.  The Trackwidget has 'Editieren' 'Suchen' 'Ordner anzeigen' ...etc.  I just dont know how to make the translation for them.

**Comment by othmar52** [comment]
i have [added](https://github.com/othmar52/slimpd/commit/0932516eec98adc53ab2a8dc31c48b34894dedb9) the translations you mentioned

In case you are interested how to find this hardcoded crap:
```
cd /path/to/your/slimpd/
grep -Ri 'Ordner anzeigen' templates/
```
should list all the files

**Comment by killhellokitty** [comment]
Okay, cool.  I'll give it a look.

**Comment by killhellokitty** [comment]
Added pull request for additional translations made on July 27th 2016

**Comment by othmar52** [comment]
It seems that you've already merged those translations yourself and this issue can be closed, right?
