### ISSUE TITLE
[Sphinx For Cyrillic] add Cyrillic data to sphinx and Search Form

### ISSUE THREAD

**Issue by filatovvo** [othmar52/slimpd#67]
[ScreenShot1](https://www.dropbox.com/s/g26l3no6w8tny2s/SphinxCyrillic.PNG?dl=0)
[ScreenShot2](https://www.dropbox.com/s/3ffg140hvv2ocoe/SphnixCyrillic2.PNG?dl=0)

**Comment by othmar52** [comment]
I can confirm the issue in screenshot2 and i have no idea why sphinx does not handle those characters correctly

```mysql
othmar52@machine ~ $ mysql -P9306 --protocol=tcp

mysql> SELECT itemuid,artist FROM slimpdmain WHERE itemuid=1178169;
+---------+--------------+
| itemuid | artist       |
+---------+--------------+
| 1178169 | 細野晴臣     |
+---------+--------------+
1 row in set (0,00 sec)

mysql> SELECT * FROM slimpdmain WHERE MATCH('@artist "細野晴臣"');
Empty set (0,01 sec)
```
regarding to [sphinxforum](http://sphinxsearch.com/forum/view.html?id=4177) the `charset_table` configuration of sphinx has to be extended!?

**Comment by filatovvo** [comment]
> In general it would be great to add a short description to opened issues instead of limiting to screenshot-links. Further one single task/bug/whatever per issue would be great :)

I`ll give a try ;)

I`m pulling master branch now after pull request, then i try to clean rescan all my library for testing last your commits

**Comment by filatovvo** [comment]
Your commit [9f28a64](https://github.com/othmar52/slimpd/commit/9f28a64b6e655251ff54971b5610af12903a0d60) not enough

@see #70

**Comment by filatovvo** [comment]
[Now Everything is Good On This Issue](https://www.dropbox.com/s/d4oq8ulkq1tm2gb/sphinxRussian.PNG?dl=0)

Issue Can Be closed after PR. #70

**Comment by othmar52** [comment]
Thank you!
