### ISSUE TITLE
rotating sphinx index does not work

### ISSUE THREAD

**Issue by othmar52** [othmar52/slimpd#7]
> I have run the shpinx-index and the first one runs without problem.  The
> second, script however gives this error:
> WARNING: failed to scanf pid from pid_file '/var/lib/log/searchd.pid'.
> WARNING: indices NOT rotated.

did you run the script as root or with sudo?
```
cd /your/slimpd/path
sudo ./scripts/sphinx-rotate.sh
```

**Comment by killhellokitty** [comment]
Oddly it worked without issue just now.

**Comment by othmar52** [comment]
great!
today a have added 2 more sphinx related systemchecks which should lead the user to a solution in case there are any errors.
