### ISSUE TITLE
Waveform issues

### ISSUE THREAD

**Issue by jimmyfi** [othmar52/slimpd#75]
I've been trying to get waveforms to appear on my tracks but I've been unable so far. On Systemcheck the python value for test file is same as on the website. I've tried fiddling with paths and such but no luck :/ What settings i should set / rights for files that the waveforms would appear?

PS Keep up working on this project. Liking it alot <3

**Comment by othmar52** [comment]
are you familiar with your browsers web developing tools?  
check the network tab  
there should be a request that looks like `http://YOURDOMAIN/audiojson/resolution/2500/PATH_TO_FILE`  
you can check if you  
 * get a response status `200 OK`
 * have a response body that looks like `[0,0,0,0,156,15,...234,0,0]`

**Comment by jimmyfi** [comment]
seems to be error 500 Internal server error

**Comment by jimmyfi** [comment]
Hah now it works.. had to edit php-fpm and enable exec() function :D now it draws pretty waveforms <3

**Comment by othmar52** [comment]
great. strange that this error did not appear on the system check  
anyway - i put a `check if exec() is allowed` on my huge todo list
